language: csharp
sudo: required
solution: clrzmq4.mono.sln
#dotnet: 1.0.3

matrix:
  include:
    - os: linux
      dist: trusty
      mono: latest
    - os: osx
      osx_image: xcode7.3
      mono: latest

before_install:
  - chmod a+x ./install_deps.sh
install:
  - INSTALL_LIBZMQ_MACOS=port ./install_deps.sh

before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh
